### ISSUE TITLE
Issue with boards with less than 4 width/height

### ISSUE THREAD

**Issue by multicore-real** [soni801/xwars#1]
**Describe the bug**
if you make a tilemap less than 100 x 3 the game will not work.
if you make a tilemap less than  2 x 50 the game will not work.

**To Reproduce**
1. Go to 'start'
2. Click on ' the tile maker shit'
bug

**Expected behavior**
that it would say that it can't do that "British accent.

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Version [0.0.11]

**Additional context**
YEEEET

**Comment by soni801** [comment]
Fixed in beta-0.1.3
