### ISSUE TITLE
Movement bug

### ISSUE THREAD

**Issue by multicore-real** [soni801/xwars#3]
**Describe the bug**
the 960 x 540 is bugged where when sometimes when you scroll around and play the window moves

**To Reproduce**
1. Go to 'start'
2. Click on 'start'

**Expected behavior**
it not doing that

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Version [0.0l11]

**Additional context**
no

**Comment by soni801** [comment]
Fixed in beta-0.1.2
